version: '3'

services:
  mysql:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306:3306'
    volumes:
      - /mnt/ShareOne/Docker/Projects/1/bitnami:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=dbname
    
  redis:
    image: 'sameersbn/redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - /mnt/ShareOne/Docker/Projects/1/redis:/var/lib/redis
    depends_on:
      - mysql
      
  mpool:
    image: 'bastiondata/docker_coinium:latest'
    depends_on:
      - redis
      - mysql
    volumes:
      - /mnt/ShareOne/Docker/Projects/1/config:/usr/local/bin/CoiniumServ/build/release/config
    ports:
      - 8081:80
      - 3333:3333
    links:
      - "mysql:dbname"
      - "redis"
